import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "./_components/Header/Header";
import { Footer } from "./_components/Footer";
export const metadata: Metadata = {
 title: "KDL.COM",
 description: "Generated by create next app",
};
export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
<html lang="en" suppressHydrationWarning>
<body className="flex flex-col items-center mt-[80px]">
<ThemeProvider
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
>
<Header />
         {children}
</ThemeProvider>
<Footer />
</body>
<link rel="icon" href="@/public/star.png" />
</html>
 );
}